### ISSUE TITLE
Add wpackagist by default

### ISSUE THREAD

**Issue by johnbillion** [humanmade/altis-skeleton#15]
Should the WordPress Packagist repo be added to composer.json by default? It makes it easier for users to add dependencies for WordPress plugins (and themes) that aren't on Packagist.

```json
"repositories": [
	{
		"type": "composer",
		"url": "https://wpackagist.org"
	}
]
```

**Comment by roborourke** [comment]
I remember bringing this up but can't remember @rmccue's reasoning not to right now. Possibly to ensure it's more of an opt-in sort of thing. While it is [documented here](https://github.com/humanmade/altis-documentation/blob/d3cfa95b781ed934ecd91d3f023ce43b4f42a1c6/other-docs/getting-started/third-party-plugins.md) it also seems that nearly all of our recent composer based projects have this in their `composer.json`.

**Comment by rmccue** [comment]
Closing, we can revisit in the future if we get more feedback about it.
