### ISSUE TITLE
Use absolute path to theme directory if possible

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-skeleton#17]
In Chassis (and IIRC in Local Server) we can access the actual paths on the parent filesystem, so we should use these in the demo theme.

**Comment by roborourke** [comment]
@rmccue can we get more information here please?

**Comment by roborourke** [comment]
cc @tomjn

**Comment by rmccue** [comment]
More detail:

In the base theme, we print out the location of the theme directory to go edit. In Chassis and Local Server, we now have the tools (see https://github.com/Chassis/Chassis/pull/638) to be able to instead output the full path to the theme directory, rather than a relative one inside the box.
