### ISSUE TITLE
`composer.json` `3.0.0-beta1` tag points to `altis/altis: dev-master`

### ISSUE THREAD

**Issue by ntwb** [humanmade/altis-skeleton#19]
I noticed on the weekend that the `3.0.0-beta1` packagist tag points to `altis/altis: dev-master` instead of `altis/altis: 3.0.0-beta1`

https://packagist.org/packages/altis/skeleton#3.0.0-beta1

**Comment by roborourke** [comment]
Thanks @ntwb, I messed this one up. I guess that's why we beta :/

I'll redo this tag with the correct version.

**Comment by roborourke** [comment]
Fixed!
