### ISSUE TITLE
Do we have a way to use beta/nightly build of Altis from skeleton

### ISSUE THREAD

**Issue by ivankristianto** [humanmade/altis-skeleton#31]
Before I open a feature request, I like to know if there is a way to setup a skeleton project but use Altis latest nightly build by default?

**Comment by roborourke** [comment]
hey @ivankristianto, I added how to upgrade to to or spin up the beta in the internal release post but for the nightly you could run `composer create-project altis/skeleton:dev-master --stability=dev altis-nightly`.

For any given beta or RC release it would be similar eg. `composer create-project altis/skeleton:7.0.0-beta1 --stability=beta altis7-beta`.

**Comment by roborourke** [comment]
Oh and if the intention is for contributing to Altis then ping me in Slack as we use a slightly different approach for getting set up locally.

**Comment by roborourke** [comment]
Going to close this out but feel free to message in Slack.
