### ISSUE TITLE
Skeleton does not set PHP 8.1 as default

### ISSUE THREAD

**Issue by mikelittle** [humanmade/altis-skeleton#58]
A change to make PHP 8.1 the default got accidentally reverted.

## Acceptance criteria

- [x] Composer.json must set PHP version to 8.1

---

### Ready

- [x] Is the title clear?
- [x] Is the description clear and detailed enough?
- [x] Are acceptance criteria listed?
- [x] Have any (potential) dependencies been identified?
- [x] Is an estimate/timebox assigned?
- [x] Is a priority label assigned?
- [x] Is this ticket added to an epic? (Optional)

**Comment by mikelittle** [comment]
Yes. I forgot to say as i was testing the v17 beta.

**Comment by ferschubert-hm** [comment]
Merged. Closing.
